class_name StoryData
extends RefCounted

const MAIN_STORY := [
	[
		["Narrador", "Durante tres siglos, la Corona de Ámbar mantuvo unidos a hombres, enanos y elfos bajo un mismo juramento."],
		["Narrador", "Pero en la noche sin luna, el rey Aldren desapareció y la corona amaneció partida sobre su trono."],
		["Narrador", "De sus cuatro fragmentos nació una bruma que borraba nombres, promesas y recuerdos."],
		["Maese Odran", "Aren, escucha las campanas. No anuncian una muerte, sino algo peor: un reino que comienza a olvidarse."],
		["Aren", "He soñado con una torre en ruinas y una voz encerrada bajo sus piedras."],
		["Maese Odran", "La torre es el corazón antiguo de Eryndor. Allí juraron los primeros reyes no gobernar jamás mediante el miedo."],
		["Aren", "¿Por qué me llama a mí? Soy el hijo de un herrero, no un caballero de leyenda."],
		["Maese Odran", "Porque el cristal que llevas perteneció a tu madre, y ella fue la última guardiana del juramento."],
		["Narrador", "Odran entregó al muchacho una espada sin filo. En su hoja dormía una luz semejante al alba."],
		["Maese Odran", "Viaja a Valdoria. Encuentra a la astrómante Lyra antes de que los heraldos de la Corona Hueca den contigo."],
		["Aren", "Si el reino está perdiendo su memoria, haré que recuerde quién fue. Lo juro."],
		["Narrador", "Así comenzó la Crónica del Cristal, en un camino donde hasta las sombras recordaban nombres olvidados."]
	],
	[
		["Lyra", "Las estrellas sobre Valdoria están inmóviles. Alguien ha clavado la noche al firmamento."],
		["Aren", "Busco al rey Aldren y los fragmentos de su corona. Odran dijo que tú conocías el primer camino."],
		["Lyra", "Conocerlo no significa que quiera recorrerlo. Mi orden fue acusada de traición por mirar demasiado lejos."],
		["Canciller Vael", "La ciudad necesita obediencia, no augurios. Entrega el cristal y tu crimen será olvidado."],
		["Aren", "Un perdón ofrecido antes del juicio suele esconder la culpa de quien lo concede."],
		["Lyra", "Bien dicho, caballero sin título. El fragmento de Valdoria duerme bajo la fuente del león."],
		["Canciller Vael", "Seguid cavando en el pasado. Cuando despertéis lo que yace allí, suplicaréis volver a ignorarlo."],
		["Narrador", "La fuente se abrió y mostró un mapa de fuego: cuatro ciudades unidas por un quinto juramento borrado."],
		["Lyra", "Brumaforja conserva el metal de la corona. Si Brom aún vive, nos ayudará a leer sus runas."],
		["Aren", "Entonces ya no viajo solo."],
		["Lyra", "No confundas compañía con confianza. Aún no he decidido cuál de las dos te ofrezco."],
		["Narrador", "Con Valdoria a sus espaldas, ambos siguieron la carretera que ascendía hacia las montañas humeantes."]
	],
	[
		["Brom", "La corona no fue forjada para mandar. Fue forjada para contener algo que dormía bajo Eryndor."],
		["Aren", "¿La bruma?"],
		["Brom", "La bruma es solo su aliento. Nosotros lo llamamos Vharos, el rey que nunca tuvo rostro."],
		["Lyra", "Los anales de Valdoria dicen que Vharos era una superstición de los mineros."],
		["Brom", "Los anales de Valdoria fueron escritos por hombres que jamás escucharon hablar a una montaña."],
		["Thane Brynja", "Brom rompió el sello de la Fragua Madre para salvar a su cuadrilla. Desde entonces carga con su vergüenza."],
		["Brom", "Y cargaré con ella hasta que mis huesos sean carbón. Pero no permitiré que Vael funda otro fragmento."],
		["Aren", "Ven con nosotros. Una culpa compartida puede convertirse en propósito."],
		["Brom", "Hablas demasiado bonito para alguien con una espada sin filo."],
		["Lyra", "Es su talento principal."],
		["Narrador", "Brom alzó su martillo y la runa del metal respondió al cristal de Aren."],
		["Brom", "Puerto Celestia guarda la lente capaz de mostrar aquello que el mundo ha decidido olvidar."]
	],
	[
		["Capitana Mara", "El mar retrocede cada medianoche como si temiera tocar nuestras costas."],
		["Lyra", "La lente del faro está desviando la luz estelar hacia la torre central."],
		["Brom", "Alguien convirtió vuestro observatorio en una llave."],
		["Aren", "¿Quién posee la llave?"],
		["Capitana Mara", "El almirante Ors. Partió hace veinte años y regresó ayer sin haber envejecido un solo día."],
		["Almirante Ors", "No regresé del mar, muchacho. El mar me devolvió porque ya no podía soportar mis recuerdos."],
		["Lyra", "Vharos se alimenta de memoria. Cada secreto entregado fortalece la Corona Hueca."],
		["Almirante Ors", "Tomad la lente. Pero sabed esto: el rey Aldren entró voluntariamente en la torre."],
		["Aren", "¿Voluntariamente?"],
		["Almirante Ors", "Quería salvar a su hija. Vael le prometió que Vharos podía devolver a los muertos."],
		["Brom", "Ninguna forja devuelve lo consumido. Solo fabrica una imitación."],
		["Narrador", "La lente señaló al sur, hacia el bosque donde los elfos guardaban los nombres verdaderos."]
	],
	[
		["Seris", "Deteneos. El bosque pronunció vuestros nombres antes de que cruzarais la primera raíz."],
		["Aren", "Venimos por el cuarto fragmento y por la verdad sobre mi madre."],
		["Seris", "Eira no murió defendiendo el cristal. Eligió entrar en él para cerrar el paso a Vharos."],
		["Lyra", "Entonces la voz que Aren oye..."],
		["Seris", "Es su recuerdo, preservado en luz. Pero cada vez que responde, el sello se debilita."],
		["Aren", "He pasado mi vida deseando escucharla una vez más."],
		["Seris", "Y Vharos ha pasado siglos esperando ese deseo."],
		["Brom", "Los deseos son mineral peligroso. Se quiebran justo cuando crees haberles dado forma."],
		["Matriarca Elowen", "Seris, acompáñalos. Tu exilio termina cuando decidas proteger algo más que tu propia pena."],
		["Seris", "No lucho por coronas humanas. Lucho para que el bosque conserve los nombres de sus muertos."],
		["Aren", "Entonces luchamos por lo mismo."],
		["Narrador", "Los cuatro juraron encontrarse ante la torre, aunque ninguno sabía qué parte de sí tendría que dejar allí."]
	],
	[
		["Rey Aldren", "Llegáis tarde. Mi hija ya respira detrás de esta puerta."],
		["Lyra", "Lo que respira conoce sus recuerdos, majestad, pero no es vuestra hija."],
		["Canciller Vael", "¿Importa la diferencia si un padre vuelve a oír la voz que ama?"],
		["Aren", "Importa cuando esa voz exige el olvido de todo un reino."],
		["Vharos", "Yo no robo recuerdos. Os libero del peso de haber fracasado."],
		["Brom", "Mis fracasos son míos. Ni un dios hueco tiene derecho a cargarlos por mí."],
		["Seris", "Sin dolor, los nombres son sonidos vacíos. Sin memoria, el amor no significa nada."],
		["Rey Aldren", "Si cierro la puerta, la perderé por segunda vez."],
		["Aren", "No. La recordaréis sin convertir a los vivos en su tumba."],
		["Narrador", "Aldren dejó caer el fragmento. Por primera vez en años, lloró como un hombre y no como un rey."],
		["Lyra", "La Corona Hueca está expuesta. Aren, decide qué clase de juramento ocupará su lugar."],
		["Aren", "Uno que ninguna corona pueda poseer: recordar juntos, incluso aquello que duele."]
	]
]

const CITY_LINES := {
	"valdoria": [
		["Mercader Tavio", "Antes vendía especias de cuatro regiones. Ahora los guardias llaman contrabando a cualquier aroma que no reconozcan."],
		["Niña de la fuente", "El león de piedra habla por las noches. Dice que tuvo otro nombre, pero nadie consigue recordarlo."],
		["Guardia Elric", "No preguntes por el rey en voz alta. Las paredes del palacio tienen oídos y los oídos llevan uniforme."],
		["Panadera Mirea", "Cada amanecer horneo una hogaza extra para mi esposo. Murió hace siete años, pero hoy he olvidado su rostro."],
		["Lyra", "La bruma no borra los hechos de golpe. Empieza llevándose los detalles que nos hacen humanos."],
		["Monje Cael", "La campana mayor se agrietó la noche de la desaparición. Aun así suena cuando alguien pronuncia la verdad."],
		["Aren", "Entonces debemos darle muchas razones para sonar."],
		["Costurera Ada", "He cosido capas para tres reyes. Aldren era el único que agradecía a quien sostenía la aguja."],
		["Veterano Joren", "Vael ganó la guerra del este sin librar una batalla. Convenció al enemigo de que ya había perdido."],
		["Estudiante Nessa", "Los libros de historia tienen páginas nuevas. La tinta está fresca, pero los profesores juran que siempre estuvieron allí."],
		["Bibliotecario Senn", "Escondimos los textos antiguos bajo tratados de jardinería. La tiranía rara vez consulta cómo podar rosales."],
		["Noble Alric", "El orden exige sacrificios. Preferiría olvidar una canción antes que ver arder la ciudad."],
		["Música callejera", "¿Una canción? El último verso desaparece de mi cabeza cada vez que intento tocarlo."],
		["Brom", "Golpea las notas como si fueran metal. Algunas memorias necesitan martillo."],
		["Vendedora de flores", "Estas campanillas solo crecen donde alguien cumplió una promesa. Este año casi no han florecido."],
		["Sirviente de palacio", "El rey cenaba solo desde la muerte de la princesa. Vael siempre dejaba un segundo plato frente a él."],
		["Lyra", "No era consuelo. Era una herida mantenida abierta."],
		["Cochero Bran", "Llevé un carruaje sellado a la torre. Dentro lloraba alguien con la voz del rey, aunque el rey viajaba a mi lado."],
		["Aren", "Vharos ya fabricaba imitaciones antes de abrirse la corona."],
		["Capitana de guardia", "Mis órdenes dicen que os arreste. Mi memoria dice que vuestra madre me salvó en el paso de Aster."],
		["Capitana de guardia", "Marchaos antes de que las órdenes pesen más que la memoria."],
		["Anciano del banco", "Eira se sentaba aquí para dar de comer a las palomas. Nunca vestía como una heroína."],
		["Aren", "Quizá los héroes solo parecen héroes cuando ya no están para contradecir la historia."],
		["Relojero Fen", "Todos mis relojes pierden el mismo minuto a medianoche. Algo sucede durante ese minuto robado."],
		["Aprendiz real", "Encontré cera negra en el sello del canciller. Huele a las criptas bajo la catedral."],
		["Sacerdotisa Ilya", "No rezamos para que los dioses resuelvan nuestro dolor. Rezamos para no convertirlo en crueldad."],
		["Mendigo Ro", "La gente me da monedas para olvidar que me ha visto. Últimamente funciona demasiado bien."],
		["Seris", "Las ciudades levantan muros contra ejércitos, pero dejan entrar cualquier mentira bien vestida."],
		["Heraldo", "Por decreto del canciller, toda reunión de más de cuatro recuerdos queda prohibida."],
		["Brom", "En Brumaforja llamaríamos a eso una invitación."],
		["Posadera Celma", "Hay habitaciones libres, aunque algunas amanecen con equipaje de huéspedes que nadie recuerda haber recibido."],
		["Cartógrafo Pell", "Los caminos cambian de sitio en mis mapas. Solo la carretera a la torre permanece inmóvil."],
		["Lyra", "Porque no es un destino. Es el punto hacia el que están cayendo todos los demás."],
		["Herrero Darom", "La espada de Aren no está sin filo. Su metal se niega a cortar aquello que no considera enemigo."],
		["Aren", "Entonces espero estar a la altura de su juicio."],
		["Madre preocupada", "Mi hijo juega a ser heraldo de Vael. Ayer me ordenó olvidar que había roto una ventana."],
		["Actor ambulante", "Representábamos la caída del Tirano Sin Rostro. Ahora el censor dice que nunca existió tal leyenda."],
		["Seris", "Cuando prohíben una historia es porque aún temen su final."],
		["Jardinero real", "Las rosas negras crecieron el día que Aldren entró en la torre. Sus raíces apuntan hacia el trono."],
		["Narrador", "Bajo el bullicio de Valdoria, cada voz conservaba una astilla distinta de la verdad."]
	],
	"brumaforja": [
		["Maestra Runa", "Aquí cada martillo lleva el nombre de quienes lo usaron. Un artesano sin memoria fabrica armas sin propósito."],
		["Minero Keld", "Oí cantar al mineral negro. Prometía vetas infinitas a cambio de un solo recuerdo feliz."],
		["Brom", "Y supongo que escuchaste la oferta completa."],
		["Minero Keld", "No. Pensé en mi hija y corrí hasta quedarme sin botas."],
		["Thane Brynja", "La montaña no está enfadada. Está asustada, y una montaña asustada puede sepultar un reino."],
		["Fundidor Orik", "El fragmento de corona se funde a una temperatura que convierte el hierro en vapor."],
		["Lyra", "Porque no responde al calor, sino a la intención de quien lo sostiene."],
		["Guardia de ceniza", "Vael envió diplomáticos. Sus guantes no dejaron huellas y sus sombras miraban en otra dirección."],
		["Cocinera Hilda", "La sopa de piedra necesita paciencia, raíz amarga y una piedra que no haya escuchado discursos humanos."],
		["Aren", "Ese último ingrediente debe de ser raro."],
		["Cocinera Hilda", "Cada año más raro, muchacho."],
		["Niño Dori", "Brom me enseñó a tallar runas. La mía significa hogar, pero parece una patata."],
		["Brom", "Todos los hogares parecen patatas vistos desde suficiente altura."],
		["Cronista de piedra", "No escribimos en papel. La piedra obliga a pensar antes de dejar una estupidez para mil años."],
		["Seris", "Los árboles hacen lo mismo, aunque suelen ser más discretos al juzgar."],
		["Ingeniera Veka", "El ascensor de magma puede bajar hasta la cámara sellada. Subir es la parte que aún no he resuelto."],
		["Lyra", "Me tranquiliza tu honestidad y me preocupa tu entusiasmo."],
		["Cantero Ulm", "La estatua de la entrada representa al primer thane. Nadie recuerda por qué tiene alas."],
		["Brom", "No son alas. Son sus cejas. El escultor era un adulador."],
		["Viuda Sigrid", "Mi esposa cayó en la galería doce. Mientras yo recuerde su risa, la mina no habrá conseguido quedárselo todo."],
		["Aren", "Luchamos para que nadie tenga que entregar ese recuerdo."],
		["Mercader de gemas", "Los cristales azules guardan sonidos. Este contiene una nana de hace cuatrocientos años."],
		["Lyra", "No lo vendas. Hay canciones que deberían pertenecer a todos."],
		["Aprendiz Fenn", "He roto siete espadas esta semana."],
		["Maestra Runa", "Entonces has descubierto siete maneras de no forjar una espada."],
		["Vigilante Tor", "La puerta profunda tiene cinco cerraduras, pero anoche apareció abierta desde dentro."],
		["Brom", "Selladla con una sexta y poned a alguien sensato a vigilar."],
		["Vigilante Tor", "¿Conoces a alguien?"],
		["Brom", "No, por eso dije que lo buscarais."],
		["Sacerdote de la llama", "El fuego recuerda todas las formas que destruye. Por eso baila cuando reconoce un rostro."],
		["Seris", "En mi bosque decimos lo mismo del agua. Tal vez los elementos discuten cuando no miramos."],
		["Soldado herido", "Combatí junto a Eira. Su luz no cegaba al enemigo; le mostraba aquello en lo que podía convertirse."],
		["Aren", "Eso explica por qué algunos bajaban las armas."],
		["Cervecera Dagna", "La cerveza de humo hace olvidar una noche. Últimamente nadie la compra: la bruma ofrece lo mismo gratis."],
		["Lyra", "La diferencia es que tu cerveza devuelve dolor de cabeza. La bruma no devuelve nada."],
		["Explorador Noll", "Encontré huellas humanas bajo la lava. Caminaban hacia arriba por la pared."],
		["Brom", "Vharos está enseñando a sus sombras a usar el mundo."],
		["Thane Brynja", "Si la corona cae, Brumaforja no se arrodillará ante otro rey."],
		["Aren", "No he venido a buscar súbditos. He venido a buscar aliados."],
		["Narrador", "En Brumaforja, la verdad era golpeada, enfriada y vuelta a golpear hasta que podía sostenerse sola."]
	],
	"celestia": [
		["Capitana Mara", "Todo puerto vive de despedidas. El nuestro empieza a vivir también de regresos imposibles."],
		["Marinero Sol", "Mi barco volvió sin tripulación, pero cada hamaca seguía balanceándose."],
		["Lyra", "¿El cuaderno de bitácora?"],
		["Marinero Sol", "Solo contenía una frase: el mar recuerda por nosotros."],
		["Astrónoma Valea", "Hay una quinta constelación entre las cuatro estaciones. Solo aparece reflejada en agua quieta."],
		["Aren", "La torre central."],
		["Astrónoma Valea", "No. Una puerta debajo de la torre."],
		["Farero Timo", "La lente se enciende aunque apague la llama. Algo en tierra firme nos está observando a través de ella."],
		["Brom", "Romperla sería sencillo."],
		["Lyra", "Y estudiar por qué funciona sería útil."],
		["Brom", "Por eso nunca terminamos una discusión antes del desayuno."],
		["Vendedora de redes", "Mis nudos atrapan peces, promesas y dedos torpes. Hoy solo quedan dedos torpes."],
		["Seris", "Los peces sienten la bruma antes que nosotros. Se han marchado a aguas con mejores recuerdos."],
		["Niña Lume", "Mi abuelo está en una estrella. Le dejo una lámpara para que encuentre el puerto."],
		["Aren", "Estoy seguro de que puede verla."],
		["Niña Lume", "Claro que puede. Las estrellas miran hacia abajo porque nos echan de menos."],
		["Cartógrafa Iris", "Las corrientes dibujan una corona alrededor del continente. Falta una joya al norte."],
		["Lyra", "Brumaforja. Los cuatro fragmentos también alteran el mar."],
		["Buceador Ren", "En el fondo hay una ciudad idéntica a esta, pero sus campanas suenan hacia dentro."],
		["Seris", "No regreses. Algunas ruinas sueñan con reemplazar aquello que las contempla."],
		["Posadero Azul", "Acepto moneda, historias o una canción. No acepto profecías desde que una no pagó su habitación."],
		["Brom", "Tengo una historia sobre una profecía que pagó de más."],
		["Posadero Azul", "Eso suena sospechosamente a una deuda."],
		["Mercader coralino", "Este coral crece formando letras antiguas. La última palabra que escribió fue hambre."],
		["Aren", "Guardadlo lejos de la lente."],
		["Sacerdotisa de mareas", "El océano perdona porque destruye las huellas, no porque olvide los pasos."],
		["Lyra", "Quizá ese sea el error de Aldren: confundir olvido con perdón."],
		["Grumete Nilo", "Quiero navegar hasta donde termina el mapa."],
		["Capitana Mara", "El mapa termina cuando al cartógrafo se le acaba el valor, no cuando se acaba el mundo."],
		["Relojera astral", "Cada estrella es un reloj. Algunas cuentan hacia el futuro; otras, hacia una noche que ya ocurrió."],
		["Aren", "¿Cuál cuenta hacia nosotros?"],
		["Relojera astral", "La que acaba de apagarse."],
		["Pescador Olan", "Aldren venía de incógnito. Preguntaba si el mar podía devolver a una persona."],
		["Seris", "¿Qué le respondiste?"],
		["Pescador Olan", "Que devuelve cuerpos, madera y secretos, pero nunca el mismo viaje."],
		["Almirante Ors", "Vael no mintió al rey. Eso lo hace más peligroso: le ofreció una verdad incompleta."],
		["Lyra", "Las mentiras más resistentes están construidas alrededor de una verdad que nadie quiere perder."],
		["Campanera", "Cuando la marea llegue al séptimo escalón, tocad tres veces. Si oís cuatro golpes, no miréis atrás."],
		["Brom", "¿Qué ocurre si miro?"],
		["Narrador", "Puerto Celestia guardaba sus secretos como el mar: a plena vista y demasiado profundos para alcanzarlos."]
	],
	"sylvaran": [
		["Seris", "No toques las luces azules. Son recuerdos que aún no han decidido a quién pertenecen."],
		["Jardinera Naia", "Cada árbol guarda un nombre en su anillo más joven. La bruma está arrancando esos anillos desde dentro."],
		["Aren", "¿Puede curarse?"],
		["Jardinera Naia", "Sí, si la verdad vuelve antes de la próxima luna. Los bosques son pacientes, no inmortales."],
		["Matriarca Elowen", "Los humanos llaman eternidad a cualquier cosa que esperen que sobreviva a sus errores."],
		["Brom", "Los enanos lo llamamos garantía y cobramos extra."],
		["Lyra", "Empiezo a comprender vuestra economía."],
		["Arquero Fael", "Seris fue expulsada por abrir el Sendero de Plata a refugiados humanos."],
		["Seris", "Fui expulsada por desobedecer. Que la orden fuera indigna solo hizo más fácil elegir."],
		["Tejedora de hojas", "Esta capa cambia con las estaciones. Ahora permanece gris aunque el bosque sea verano."],
		["Lyra", "La bruma está borrando el concepto de cambio. Quiere un mundo detenido."],
		["Anciano Thalan", "Conocí a Eira cuando aún se enfadaba si la llamaban guardiana."],
		["Aren", "¿Cómo quería que la llamaran?"],
		["Anciano Thalan", "Por su nombre. A veces el destino es una forma educada de dejar de ver a la persona."],
		["Músico de raíces", "Toco para que el gran árbol sueñe. Últimamente sueña con una corona vacía llena de dientes."],
		["Brom", "He forjado coronas y he visto dientes. Nunca debieron compartir diseño."],
		["Niña elfa", "¿Los humanos de verdad olvidan cosas después de solo cien años?"],
		["Aren", "A veces después de una tarde."],
		["Niña elfa", "Debe de ser emocionante poder sorprenderse tantas veces."],
		["Custodio Orren", "La cámara de nombres solo se abre ante alguien dispuesto a entregar el suyo."],
		["Seris", "Es una prueba de humildad, no un sacrificio. Quien sabe quién es puede caminar sin etiqueta."],
		["Herborista Veya", "La flor de luna cura venenos. La raíz de luna cura las excusas para no tomar la medicina."],
		["Brom", "Necesitaré dos raíces para Lyra."],
		["Lyra", "Y yo una pala para ti."],
		["Vigía del dosel", "Sombras con armadura avanzan desde el norte. No pisan ramas, pero las ramas se rompen."],
		["Aren", "Los heraldos de Vael."],
		["Seris", "No. Algo más antiguo está aprendiendo su forma."],
		["Escultor Leth", "Tallamos estatuas en madera viva. Si no les gusta el resultado, crecen hacia otra postura."],
		["Lyra", "Un método crítico admirable."],
		["Guardián del estanque", "El agua muestra el recuerdo que más temes perder. No bebas si tienes sed de respuestas."],
		["Aren", "Vi a mi madre alejándose."],
		["Guardián del estanque", "Entonces aún no temes perderla. Temes que haya elegido marcharse."],
		["Cazadora Mae", "No matamos al ciervo blanco. Cuando aparece, seguimos sus huellas hasta alguien que necesita ayuda."],
		["Brom", "En mis montañas seguimos cabras. Suelen guiarnos hasta otra cabra."],
		["Escriba Aelis", "El pacto original tenía cinco firmas: humano, enano, elfo, marino y una quinta borrada."],
		["Lyra", "La firma de la propia tierra. La corona no gobernaba Eryndor; negociaba con ella."],
		["Matriarca Elowen", "Si reconstruís la corona, no la entreguéis a otro rey. Devolvedla al juramento."],
		["Aren", "¿Puede un reino existir sin que alguien lo posea?"],
		["Seris", "Un bosque existe así desde antes de que inventarais los tronos."],
		["Narrador", "En Sylvaran, cada hoja susurraba que recordar no era mirar atrás, sino elegir qué llevar hacia delante."]
	]
}

static func get_story_lines(chapter: int) -> Array:
	var safe_chapter: int = clampi(chapter, 0, MAIN_STORY.size() - 1)
	return MAIN_STORY[safe_chapter]

static func get_city_lines(city_id: String) -> Array:
	var lines: Array = CITY_LINES.get(city_id, [])
	return lines

static func dialogue_count() -> int:
	var total := 0
	for scene in MAIN_STORY:
		total += scene.size()
	for lines in CITY_LINES.values():
		total += lines.size()
	return total
